### ISSUE TITLE
Can we use range of values (1-5) for a protected variable

### ISSUE THREAD

**Issue by neuideas** [cran/fairmodels#1]
Good day everyone

About fairmodels, I have an input metric with values from 1-30 (I make it from numeric to nominal) which I want to put as a protected variable. We can evaluate its fairness for individual values (e.g. 1, 2, 3 or so) but can we check it for a range of values. I mean what if we want to check the fairness of a model like: This model has less fairness when the protected variable has a range 1-6 and has less bias when the range of values is between 15-25. 

I know this case might be different than originally the package has developed for but just asking if it is possible to implement.?

Thanks

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by neuideas** [comment]
Ok thank you.

Best regards
